# Generated by Django 3.2.9 on 2021-11-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('pic', models.FileField(default='', upload_to='profile/')),
            ],
        ),
    ]
