# Generated by Django 3.2.9 on 2021-11-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_fir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='fir_at',
            new_name='fir_type',
        ),
        migrations.AddField(
            model_name='fir',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
