# Generated by Django 3.2.9 on 2021-11-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_auto_20211117_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='fir_type',
            field=models.CharField(max_length=50),
        ),
    ]
