# Generated by Django 3.2.9 on 2021-11-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_alter_fir_fir_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='posted_at',
            new_name='fir_at',
        ),
    ]
