# Generated by Django 3.2.9 on 2021-11-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_rename_posted_at_fir_fir_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('dis', models.TextField()),
                ('comp_type', models.CharField(max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('comp_pic', models.FileField(blank=True, null=True, upload_to='complain')),
                ('status', models.CharField(default='open', max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.citizen')),
            ],
        ),
    ]
