# Generated by Django 3.2.9 on 2021-11-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0006_complain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='dis',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='dis',
            new_name='des',
        ),
    ]
