# Generated by Django 3.2.9 on 2021-11-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0007_auto_20211120_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='email',
            new_name='cemail',
        ),
    ]
