# Generated by Django 3.2.9 on 2021-12-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0010_alter_complain_comp_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='posted_at',
            new_name='comp_at',
        ),
    ]
