# Generated by Django 3.2.9 on 2021-11-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissioner',
            old_name='email',
            new_name='cemail',
        ),
    ]
