# Generated by Django 3.2.9 on 2021-11-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_email_commissioner_cemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissioner',
            old_name='cemail',
            new_name='email',
        ),
    ]
